// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABaJQ5CasMi31sPlnFw5Uk-vGMX6Qb0to',
    appId: '1:6743819472:web:5355cc3e069fa653870ad5',
    messagingSenderId: '6743819472',
    projectId: 'umbrella4u-notifs',
    authDomain: 'umbrella4u-notifs.firebaseapp.com',
    storageBucket: 'umbrella4u-notifs.firebasestorage.app',
    measurementId: 'G-L89E8RKWGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXCLHKG44crzQsgduJ_DEtx6cD14E6DKg',
    appId: '1:6743819472:android:ae109d660b6187a6870ad5',
    messagingSenderId: '6743819472',
    projectId: 'umbrella4u-notifs',
    storageBucket: 'umbrella4u-notifs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfjquW8nqqyd26pw_9f5Gw4-Ug6_41w4g',
    appId: '1:6743819472:ios:bf48d3275097e2d6870ad5',
    messagingSenderId: '6743819472',
    projectId: 'umbrella4u-notifs',
    storageBucket: 'umbrella4u-notifs.firebasestorage.app',
    iosBundleId: 'ca.umbrella4u.haven',
  );
}
